#undef TAPPING_TERM
#define TAPPING_TERM 230

#define PERMISSIVE_HOLD

#define COMBO_TERM 60

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 120000

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 20

#define SERIAL_NUMBER "4Wo53/yom6Ml"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

